import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Gnpay Signup Page",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="flex flex-col items-center justify-center w-screen h-screen bg-black">
      <Link
        className="p-4 rounded-lg border border-white min-w-[200px] my-2 text-white"
        href={"/login"}
      >
        Login
      </Link>
      <Link
        className="p-4 rounded-lg border border-white min-w-[200px] my-2 text-white"
        href={"/register"}
      >
        Register
      </Link>
      <Link
        className="p-4 rounded-lg border border-white min-w-[200px] my-2 text-white"
        href={"/dashboard"}
      >
        Dashboard
      </Link>
    </main>
  );
}
